### ISSUE TITLE
Setup auth module for API authentication

### ISSUE THREAD

**Issue by trouni** [dmbf29/predictor-api#5]
## Objective

Create a `/auth` route for the Vue app to authenticate a user. There will be no session since the FE and BE are separated.

## TODO

- [ ] Install the `devise_token_auth` gems
- [ ] [Setup](https://devise-token-auth.gitbook.io/devise-token-auth/config) `devise_token_auth`
- [ ] Test the auth routes in Postman
